name: Protection check
on: pull_request_target

jobs:
  forkedpr-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Copy code
        uses: actions/checkout@v2

